import assert from 'node:assert/strict'
import test from 'node:test'
import { CHAIN_HEX, CONTRACT, RULE, PRICE, FundingError, parseConfig, parseView, fundData, type View, type Config } from '../../src/testnet-funding/contracts.ts'
import { FundingController, statusText } from '../../src/testnet-funding/controller.ts'
import { createFundingApi, type FundingApi } from '../../src/testnet-funding/api.ts'
import { selectMetaMask, type Provider } from '../../src/testnet-funding/wallet.ts'
const payer='0x'+'12'.repeat(20), other='0x'+'34'.repeat(20), intent='0x'+'56'.repeat(32), txHash='0x'+'78'.repeat(32)
const now=1000000
const config:Config={chainId:10143,contract:CONTRACT,ruleVersion:RULE,priceWei:PRICE,testOnly:true,configured:true}
function fixture(): View { return {operation:{budgetViolation:false,finalizedReceipt:null,receiptConflict:null,id:'original',intentId:intent,batchId:'0x'+'ab'.repeat(32),payer,status:'PREPARED',txHash:null,errorCode:null,submitted:false,receiptBlock:null,receiptBlockHash:null,finalizedBlock:null,gasFeeWei:null,scanThrough:null},intent:{chainId:10143,to:CONTRACT,data:fundData(intent),valueWei:PRICE,quantity:1,ruleVersion:RULE,gasLimitCap:250000,maxFeePerGasCapWei:'200000000000'},review:null,accounting:null} }
function transaction() { return {from:payer,to:CONTRACT,chainId:CHAIN_HEX as '0x279f',nonce:'0x1',data:fundData(intent),value:'0x38d7ea4c68000',gas:'0x30d40',maxFeePerGas:'0x2e90edd000',maxPriorityFeePerGas:'0x77359400',type:'0x2' as const} }
class Wallet implements Provider {
  isMetaMask=true; account=payer; chain=CHAIN_HEX; calls:string[]=[]; listeners=new Map<string,Set<(...args:unknown[])=>void>>(); send:()=>Promise<unknown>=async()=>txHash
  async request({method}:{method:string;params?:unknown[]}) { this.calls.push(method); if(method==='eth_accounts'||method==='eth_requestAccounts') return [this.account]; if(method==='eth_chainId') return this.chain; if(method==='wallet_switchEthereumChain') {this.chain=CHAIN_HEX;this.emit('chainChanged');return null} if(method==='eth_sendTransaction') return this.send(); throw new Error('unexpected') }
  on(event:string,fn:(...args:unknown[])=>void) { if(!this.listeners.has(event)) this.listeners.set(event,new Set()); this.listeners.get(event)!.add(fn) }
  removeListener(event:string,fn:(...args:unknown[])=>void) { this.listeners.get(event)?.delete(fn) }
  emit(event:string) { this.listeners.get(event)?.forEach(fn=>fn()) }
}
function setup() {
  let view=fixture(); const calls:string[]=[]; const wallet=new Wallet()
  const api:FundingApi={config:async()=>structuredClone(config),operation:async()=>structuredClone(view),session:async()=>{calls.push('session');return structuredClone(view)},review:async()=>{calls.push('review');view.review={id:'review',expiresAt:now+120000,transaction:transaction()};return structuredClone(view)},submitStart:async()=>{calls.push('submit');view.operation.submitted=true;view.operation.status='SUBMISSION_UNKNOWN';return {...structuredClone(view),transaction:transaction()}},transaction:async(hash)=>{calls.push('transaction');view.operation.txHash=hash;view.operation.status='BROADCAST';return structuredClone(view)},reconcile:async()=>{calls.push('reconcile');return structuredClone(view)}}
  const controller=new FundingController(api,()=>wallet,()=>now)
  return {api,controller,wallet,calls,getView:()=>view}
}
async function reviewed(s:ReturnType<typeof setup>) {await s.controller.load();await s.controller.connect();await s.controller.review();assert.ok(s.controller.state.review)}
test('loading/reconciling never connects, switches, signs or creates a session',async()=>{const s=setup();await s.controller.load();await s.controller.reconcile();assert.deepEqual(s.wallet.calls,[]);assert.deepEqual(s.calls,['reconcile'])})
test('explicit successful send is once, stable intent survives repeated calls',async()=>{const s=setup();await reviewed(s);await Promise.all([s.controller.submit(),s.controller.submit()]);await s.controller.submit();await s.controller.review();await s.controller.start();assert.equal(s.wallet.calls.filter(x=>x==='eth_sendTransaction').length,1);assert.equal(s.calls.filter(x=>x==='submit').length,1);assert.equal(s.calls.filter(x=>x==='session').length,0);assert.equal(s.controller.state.view?.operation.txHash,txHash);assert.equal(s.controller.state.view?.operation.intentId,intent)})
for(const result of ['4001','nohash','failure'] as const) test(`post marker ${result} stays UNKNOWN, never retries`,async()=>{const s=setup();s.wallet.send=async()=>{if(result==='4001') throw {code:4001,message:'secret'};if(result==='failure') throw new Error('private provider details');return undefined};await reviewed(s);await s.controller.submit();assert.equal(s.controller.state.consumed,true);assert.equal(statusText(s.controller.state),'付款结果待核，请查询原操作');await s.controller.submit();await s.controller.start();await s.controller.reconcile();assert.equal(s.wallet.calls.filter(x=>x==='eth_sendTransaction').length,1);assert.equal(s.controller.state.view?.operation.status,'SUBMISSION_UNKNOWN')})
test('submit response loss stops all send attempts, retains consumed state after refresh',async()=>{const s=setup(),original=s.api.submitStart;s.api.submitStart=async id=>{await original(id);throw new FundingError('CONNECTION_UNAVAILABLE')};await reviewed(s);await s.controller.submit();await s.controller.submit();await s.controller.reconcile();assert.equal(s.calls.filter(x=>x==='submit').length,1);assert.equal(s.wallet.calls.includes('eth_sendTransaction'),false);assert.equal(s.controller.state.consumed,true);assert.equal(s.controller.state.view?.operation.status,'SUBMISSION_UNKNOWN')})
for(const event of ['accountsChanged','chainChanged','disconnect']) test(`${event} invalidates review before submit`,async()=>{const s=setup();await reviewed(s);s.wallet.emit(event);assert.equal(s.controller.state.review,null);await s.controller.submit();assert.equal(s.calls.includes('submit'),false)})
test('account changes during server review invalidate delayed response',async()=>{const s=setup(),original=s.api.review;s.api.review=async account=>{const v=await original(account);s.wallet.emit('accountsChanged');return v};await s.controller.load();await s.controller.connect();await s.controller.review();assert.equal(s.controller.state.review,null);assert.equal(s.controller.state.error,'WALLET_CHANGED')})
test('account changes after marker prevents send, retains UNKNOWN',async()=>{const s=setup(),original=s.api.submitStart;s.api.submitStart=async id=>{const v=await original(id);s.wallet.account=other;s.wallet.emit('accountsChanged');return v};await reviewed(s);await s.controller.submit();assert.equal(s.controller.state.consumed,true);assert.equal(s.wallet.calls.includes('eth_sendTransaction'),false);assert.equal(s.controller.state.error,'SUBMISSION_UNKNOWN')})
test('silent current account or chain change is doublechecked',async()=>{for(const kind of ['account','chain']) {const s=setup();await reviewed(s);if(kind==='account') s.wallet.account=other;else s.wallet.chain='0x1';await s.controller.submit();assert.equal(s.calls.includes('submit'),false);assert.equal(s.controller.state.review,null)}})
test('wrong wallet never gets review approval',async()=>{const s=setup();s.wallet.account=other;await s.controller.load();await s.controller.connect();await s.controller.review();assert.equal(s.calls.includes('review'),false);assert.equal(s.controller.state.error,'WRONG_ACCOUNT')})
test('expired quote blocks marker',async()=>{const s=setup();await reviewed(s);s.controller.state.review!.expiresAt=now;await s.controller.submit();assert.equal(s.calls.includes('submit'),false);assert.equal(s.controller.state.error,'REVIEW_EXPIRED')})
test('server consumed by another tab permits original query only',async()=>{const s=setup();s.getView().operation.status='SUBMISSION_UNKNOWN';s.getView().operation.submitted=true;await s.controller.load();await s.controller.connect();await s.controller.review();await s.controller.submit();assert.deepEqual(s.wallet.calls,[]);assert.equal(s.calls.includes('submit'),false)})
test('cookie lost cannot silently create another session',async()=>{const s=setup();s.api.operation=async()=>{throw new FundingError('ORIGINAL_ACCESS_REQUIRED')};s.api.session=async()=>{throw new FundingError('ORIGINAL_ACCESS_REQUIRED')};await s.controller.load();assert.equal(s.controller.state.error,'ORIGINAL_ACCESS_REQUIRED');assert.deepEqual(s.calls,[]);await s.controller.start();assert.equal(s.controller.state.view,null);assert.deepEqual(s.wallet.calls,[])})
test('ambiguous provider selection never picks the first wallet',()=>{const wallet=new Wallet();assert.equal(selectMetaMask({providers:[{isMetaMask:false,request:wallet.request},wallet],request:wallet.request}),wallet);assert.throws(()=>selectMetaMask({providers:[wallet,new Wallet()],request:wallet.request}),/WALLET_AMBIGUOUS/);assert.throws(()=>selectMetaMask({isMetaMask:true,isRabby:true,request:wallet.request}),/METAMASK_NOT_FOUND/)})
for(const [key,value] of [['from',other],['to',other],['chainId','0x1'],['nonce','0x01'],['data','0x'],['value','0x0'],['gas','0x3d091'],['maxFeePerGas','0x2e90edd001'],['maxPriorityFeePerGas','0x77359401'],['type','0x0'],['extra','0x0']]) test(`reject tampered wallet field ${key}`,()=>{const v=fixture();v.review={id:'r',expiresAt:now+1,transaction:{...transaction(),[key]:value}};assert.throws(()=>parseView(v),/INVALID_RESPONSE/)})
test('submit nonce mismatch from reviewed transaction prevents send',async()=>{const s=setup(),original=s.api.submitStart;s.api.submitStart=async id=>{const v=await original(id);v.transaction.nonce='0x2';return v};await reviewed(s);await s.controller.submit();assert.equal(s.controller.state.consumed,true);assert.equal(s.wallet.calls.includes('eth_sendTransaction'),false)})
test('server cannot replace original intent or campaign',async()=>{const s=setup();await s.controller.load();s.api.reconcile=async()=>{const v=fixture();v.operation.id='another';return v};await s.controller.reconcile();assert.equal(s.controller.state.view?.operation.id,'original');assert.equal(s.controller.state.error,'INVALID_RESPONSE')})
test('finality alone is not batch success',()=>{const s=setup();const v=fixture();v.operation.status='FINALIZED_SUCCESS';v.operation.submitted=true;s.controller.state.view=v;s.controller.state.consumed=true;assert.equal(statusText(s.controller.state),'链上入款已最终确认，正在核对批次');v.operation.status='ACCOUNTING_VERIFIED';assert.throws(()=>parseView(v),/INVALID_RESPONSE/);v.operation.txHash=txHash;v.operation.receiptBlock=10;v.operation.receiptBlockHash=txHash;v.operation.finalizedBlock=11;v.accounting={F:PRICE,A:PRICE,R:'0',H:'0',S:'0',liabilityWei:PRICE,contractBalanceWei:PRICE,totalFundedWei:PRICE,blockNumber:11,blockHash:txHash};parseView(v);assert.equal(statusText(s.controller.state),'测试餐款已到账，批次已核验')})
test('bad calldata, non-integer wei, changed rules and unknown fields fail closed',()=>{for(const mutate of [(v:View)=>{v.intent.data='0x'},(v:View)=>{v.intent.valueWei='1e15'},(v:View)=>{v.intent.ruleVersion=txHash},(v:View)=>{(v.intent as unknown as Record<string,unknown>).extra=1}]) {const v=fixture();mutate(v);assert.throws(()=>parseView(v),/INVALID_RESPONSE/)}assert.throws(()=>parseConfig({...config,chainId:1}),/INVALID_RESPONSE/)})
test('API uses exact same-origin route/cookie/CSRF, sanitized errors and no retry',async()=>{const calls:{url:unknown,init:RequestInit|undefined}[]=[];const api=createFundingApi((async(url,init)=>{calls.push({url,init});return new Response(JSON.stringify(fixture()),{status:200,headers:{'Content-Type':'application/json'}})}) as typeof fetch);await api.review(payer);assert.equal(calls[0].url,'/api/v1/testnet-funding/review');assert.equal(calls[0].init?.credentials,'same-origin');assert.equal((calls[0].init?.headers as Record<string,string>)['X-CP21-Request'],'1');assert.equal(calls[0].init?.body,JSON.stringify({account:payer,chainId:10143}));let attempts=0;const bad=createFundingApi((async()=>{attempts++;return new Response(JSON.stringify({code:'secret https://token'}),{status:500})}) as typeof fetch);await assert.rejects(bad.reconcile(),/REQUEST_FAILED/);assert.equal(attempts,1)})
test('unmount while marker is in flight prevents wallet send',async()=>{const s=setup(),original=s.api.submitStart;s.api.submitStart=async id=>{const v=await original(id);s.controller.dispose();return v};await reviewed(s);await s.controller.submit();assert.equal(s.wallet.calls.includes('eth_sendTransaction'),false);assert.equal(s.controller.state.consumed,true)})
test('wallet changing after broadcast still attaches hash to original payer',async()=>{const s=setup();s.wallet.send=async()=>{s.wallet.account=other;s.wallet.emit('accountsChanged');return txHash};await reviewed(s);await s.controller.submit();assert.equal(s.controller.state.view?.operation.txHash,txHash);assert.equal(s.controller.state.view?.operation.payer,payer)})

test('wallet timeout leaves original operation queryable with no second send',async()=>{const s=setup();s.wallet.send=()=>new Promise(()=>{});const controller=new FundingController(s.api,()=>s.wallet,()=>now,1);await controller.load();await controller.connect();await controller.review();await controller.submit();assert.equal(controller.state.busy,false);assert.equal(controller.state.error,'SUBMISSION_UNKNOWN');await controller.submit();await controller.reconcile();assert.equal(s.wallet.calls.filter(x=>x==='eth_sendTransaction').length,1);assert.equal(controller.state.consumed,true)})

test('HTTP200 cached DTO reports stale and visible error until completed refresh',async()=>{
  const view=fixture();view.operation.submitted=true;view.operation.status='FINALIZED_SUCCESS';view.operation.txHash=txHash;view.operation.receiptBlock=1;view.operation.receiptBlockHash=txHash;view.operation.finalizedBlock=1
  view.operation.finalizedReceipt={status:1,blockNumber:1,blockHash:txHash,gasFeeWei:'10'}
  const api={config:async()=>config,operation:async()=>structuredClone(view),reconcile:async()=>structuredClone(view)} as FundingApi
  const c=new FundingController(api,()=>undefined);await c.load();assert.equal(c.state.stale,false)
  for(const code of ['RPC_UNAVAILABLE','RPC_TIMEOUT','SYNC_BUDGET','RECEIPT_UNAVAILABLE']){
    view.operation.errorCode=code;await c.reconcile();assert.equal(c.state.stale,true);assert.equal(c.state.error,code);assert.equal(c.state.view?.operation.finalizedReceipt?.status,1)
  }
  view.operation.errorCode=null;await c.reconcile();assert.equal(c.state.stale,false);assert.equal(c.state.error,null);assert.equal(c.state.consumed,true)
})
test('budget violation remains prominent alongside finalized execution result',async()=>{
  const view=fixture();view.operation.submitted=true;view.operation.status='FINALIZED_REVERT';view.operation.budgetViolation=true;view.operation.errorCode='BUDGET_EXCEEDED';view.operation.txHash=txHash
  view.operation.finalizedReceipt={status:0,blockNumber:1,blockHash:txHash,gasFeeWei:'20'}
  const c=new FundingController({config:async()=>config,operation:async()=>view,reconcile:async()=>view} as FundingApi,()=>undefined)
  await c.load();assert.equal(c.state.stale,false);assert.match(statusText(c.state),/预算违规/);assert.match(statusText(c.state),/执行失败/);assert.equal(c.state.consumed,true)
  await c.reconcile();assert.match(statusText(c.state),/永久禁止再次签名/)
})
test('conflicting finalized receipt retains historical fact and reports stale',async()=>{
  const view=fixture();view.operation.submitted=true;view.operation.status='HALTED';view.operation.errorCode='FINALITY_CONFLICT'
  view.operation.finalizedReceipt={status:1,blockNumber:1,blockHash:txHash,gasFeeWei:'20'};view.operation.receiptConflict={...view.operation.finalizedReceipt,status:0}
  const c=new FundingController({config:async()=>config,operation:async()=>view} as FundingApi,()=>undefined);await c.load()
  assert.equal(c.state.stale,true);assert.equal(c.state.view?.operation.finalizedReceipt?.status,1);assert.equal(c.state.view?.operation.receiptConflict?.status,0);assert.match(statusText(c.state),/停止/)
})
