import {useEffect,useRef,useState} from 'react'
import type {AuthApi} from '../dynamic/contracts.ts'
import {parseDelivery,parseInvite,type DeliveryView,type InviteResult} from '../testnet-voucher/contracts.ts'

const messages:Record<string,string>={TESTNET_SCOPE_DENIED:'当前工作身份没有这张测试券的分发权限。',ISSUANCE_NOT_READY:'链上测试券尚未完成最终核账，不能生成领取链接。',RESTORE_QUARANTINE:'领取链接状态处于恢复隔离，请联系测试负责人。',ISSUANCE_EVIDENCE_INVALID:'发行证据当前不可用，未生成新的领取凭证。',ISSUANCE_BINDING_CONFLICT:'发行证据已变化，当前领取凭证被冻结。',INVITE_EXISTS:'私密链接已经生成。完整链接不会由服务端再次返回；如原链接尚未打开且已丢失，可主动换新。',INVITE_ALREADY_OPENED:'已有设备打开过私密链接。为避免静默换券，本片不允许自动换新。'}
const human=(ts:number)=>new Date(ts*1000).toLocaleString('zh-CN',{hour12:false})
export function TestnetDelivery({api}:{api:AuthApi}){
  const [view,setView]=useState<DeliveryView>(),[invite,setInvite]=useState<InviteResult>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false);const epoch=useRef(0)
  async function load(){const version=++epoch.current;setBusy(true);setError('');try{const next=parseDelivery(await api.request('/work/testnet-voucher'));if(version===epoch.current)setView(next)}catch(f){if(version===epoch.current)setError(messages[(f as {code?:string}).code??'']??'测试券分发状态暂不可用。')}finally{if(version===epoch.current)setBusy(false)}}
  useEffect(()=>{void load();return()=>{epoch.current++}},[api])
  async function generate(action:'create'|'rotate'){if(busy)return;setBusy(true);setError('');setCopied(false);try{const result=parseInvite(await api.request('/work/testnet-voucher/invite',{action}));setInvite(result);const next=parseDelivery(await api.request('/work/testnet-voucher'));setView(next)}catch(f){setError(messages[(f as {code?:string}).code??'']??'私密领取链接未生成，请保留原状态并重查。')}finally{setBusy(false)}}
  async function copy(){if(!invite)return;try{await navigator.clipboard.writeText(invite.url);setCopied(true)}catch{setError('浏览器未允许复制，请长按或选择链接后复制。')}}
  async function share(){if(!invite||!navigator.share)return;try{await navigator.share({title:'留膳 · 一份测试餐券',text:'这是机构伙伴私下发送的一份测试餐券，请勿转发。',url:invite.url})}catch{/* cancel does not change server state */}}
  return <section aria-labelledby="delivery-title"><p className="eyebrow">CP23 · 私密线上分发</p><h2 id="delivery-title">把这一张餐券发给领取者</h2><p>默认发送<strong>私密链接</strong>；二维码留给领取者到店后生成短时核销码。不要把长期领取链接发布到群聊、公开帖子或公账。</p>{error&&<p role="alert">{error}</p>}{view&&<dl><dt>机构伙伴</dt><dd>{view.partnerLabel}</dd><dt>私下领取标签</dt><dd>{view.recipientRef}</dd><dt>分发状态</dt><dd>{view.status==='READY'?'尚未生成链接':view.status==='LINK_CREATED'?'私密链接已生成，尚无设备打开':'已有设备打开过链接（不证明指定本人收到）'}</dd>{view.invite&&<><dt>链接有效至</dt><dd>{human(view.invite.expiresAt)}</dd></>}</dl>}{view?.status==='READY'&&<button disabled={busy} onClick={()=>void generate('create')}>生成私密领取链接</button>}{view?.status==='LINK_CREATED'&&!invite&&<button disabled={busy} onClick={()=>void generate('rotate')}>原链接丢失 · 换一个新链接</button>}{invite&&<div className="private-link-box" role="status"><strong>完整链接只在本次页面内存中显示</strong><input aria-label="私密领取链接" readOnly value={invite.url}/><div className="button-row"><button disabled={busy} onClick={()=>void copy()}>{copied?'已复制':'复制私密链接'}</button>{typeof navigator.share==='function'&&<button disabled={busy} onClick={()=>void share()}>系统分享</button>}</div><p>换新会让旧链接立即失效；一旦已有设备打开，本片不自动换新。</p></div>}<p className="fineprint">打开链接只建立这张券的受限展示会话，不核销、不拿处理权、不证明自然人身份或已经吃到餐。</p></section>
}
