import test from 'node:test'
import assert from 'node:assert/strict'
import {parseDelivery,parseDisplay,parseInvite,parseSession,recipientSecretFromHash,VoucherApiError} from '../../src/testnet-voucher/contracts.ts'
const h=(c:string)=>'0x'+c.repeat(64)
const base={chainId:10143 as const,testOnly:true as const,distribution:'PRIVATE_LINK' as const,status:'READY' as const,voucherId:h('a'),batchId:h('b'),operationId:h('c'),partnerLabel:'partner-a',recipientRef:'ref-a',linkRecoverable:false as const,invite:null}
test('recipient fragment is exact bearer form',()=>{const s='a'.repeat(43);assert.equal(recipientSecretFromHash('#/recipient/'+s),s);assert.equal(recipientSecretFromHash('#/recipient'),null);assert.equal(recipientSecretFromHash('#/recipient/bad'),null);assert.equal(recipientSecretFromHash('#/partner'),undefined)})
test('delivery/invite DTOs reject extra secret and query credential',()=>{assert.equal(parseDelivery(base).status,'READY');assert.throws(()=>parseDelivery({...base,secret:'x'}),VoucherApiError);const url='http://127.0.0.1:15207/#/recipient/'+'b'.repeat(43);assert.equal(parseInvite({url,expiresAt:1800001000,replacesPrevious:false,warning:'PRIVATE_BEARER_LINK'}).url,url);assert.throws(()=>parseInvite({url:url.replace('#/recipient/','?secret='),expiresAt:1800001000,replacesPrevious:false,warning:'PRIVATE_BEARER_LINK'}),VoucherApiError)})
test('recipient DTO has no recipientRef',()=>{const v={voucher:{chainId:10143,testOnly:true,state:'ISSUED',mealLabel:'1份标准餐',valueWei:'1000000000000000',voucherId:h('a'),batchId:h('b'),operationId:h('c'),partnerLabel:'partner-a',inviteExpiresAt:1800001000,sessionExpiresAt:1800000500},csrfToken:'d'.repeat(64)};assert.equal(parseSession(v).voucher.state,'ISSUED');assert.throws(()=>parseSession({...v,voucher:{...v.voucher,recipientRef:'ref-a'}}),VoucherApiError)})
test('display accepts only opaque QR plus six-digit code',()=>{assert.equal(parseDisplay({display:{qrPayload:'mealforward:testnet:v1:'+'x'.repeat(32),code:'012345',expiresAt:1800000120,nonce:1}}).code,'012345');assert.throws(()=>parseDisplay({display:{qrPayload:'http://127.0.0.1:15207/#/recipient/'+'x'.repeat(43),code:'012345',expiresAt:1800000120,nonce:1}}),VoucherApiError)})
